[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; ===== Upload via USB (bukan UART) =====
upload_protocol = esptool
;upload_speed = 115200
monitor_speed = 115200

; ===== Flash & Partition (16MB) =====
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.partitions = partitions_16mb.csv   ; custom: app=12MB, spiffs=4MB

; ===== PSRAM (OPI) =====
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1            ; USB CDC mode
    -DARDUINO_USB_CDC_ON_BOOT=1     ; Enable Serial via USB
    -DCORE_DEBUG_LEVEL=0            ; Disable debug untuk performance

    -Iinclude

lib_deps =
    lovyan03/LovyanGFX@^1.1.12
    gilmaimon/ArduinoWebsockets@^0.5.3
    bblanchon/ArduinoJson@^7.0.0
